name: Python CI # Workflow name

# To trigger the workflow we need to define events
on:
  push:
    branches:
      - main # Make sure there is a space between '-' and 'main'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # github provides containers to do the testing

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout all the code from the repository
      
      # Step 2: Setup a Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest
