name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Step 3: Verify Python installation
      - name: Check Python version
        run: python --version

      # Step 4: Install dependencies and verify pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip --version  # Ensure pip is installed correctly
          pip install -r requirements.txt

      # Step 5: Verify pytest installation
      - name: Verify pytest installation
        run: pytest --version  # This ensures pytest is installed

      # Step 6: Run tests
      - name: Run tests
        run: python -m pytest  # Run pytest using python -m for consistency
